theme: jekyll-theme-minimal
title: DeepGram
description: This is a project to make your Deep Learning project running on Telegram. DeepGram is an <a href="https://hackademia.net">Hackademia</a> project. <br> <a href="https://www.youtube.com/channel/UCZYstikbinqnokpinHExR6w">YouTube</a> <br> <a href="https://instagram.com/hackademia_net">Instagram</a>
---
layout: page
title: DeepGram Meetups Calendar
permalink: /calendar/
type: info
header_text: DeepGram Meetups Calendar
calendar: true
---
<div class="span3">
	<h3>Events</h3>
<div id="upcoming"></div><!--/span-->
</div>
<div class="span9">
	<h3>Upcoming Events</h3>
	<iframe src="https://calendar.google.com/calendar/embed?src=i8m9ckbo5l0o38bc98ocui6mp8%40group.calendar.google.com&ctz=Europe%2FRome" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe>
</div><!--/span-->
